MEGA65: mega65-core build refinements #436

diff --git a/targets/mega65/Makefile b/targets/mega65/Makefile
--- a/targets/mega65/Makefile
+++ b/targets/mega65/Makefile
@@ -37,6 +37,7 @@ MEGA65_FILES	+= sdcard-files/M65THUMB.M65 sdcard-files/MONITOR.M65 sdcard-files/
 
 MEGA65_FP_FILES	= $(addprefix $(MEGA65_CORE)/,$(MEGA65_FILES))
 MEGA65_LOCALDIR	= .sys-files-mega65-core
+
 MATRIX_TAB_VHDL = $(MEGA65_CORE)/src/vhdl/matrix_to_ascii.vhdl
 
 include ../../build/Makefile.common
@@ -44,17 +45,9 @@ include ../../build/Makefile.common
 # mega65-core has very tricky build system, it's very hard to be sure, that everything
 # is up-to-date, this is the reason for this mess
 recreatememcontent:
-	test -f "$(MEGA65_CORE)/xemu_checked_out" || $(MAKE) mega65corefetch
-	test -f "$(MEGA65_CORE)/xemu_patched" || $(MAKE) mega65patch
+	$(MAKE) $(MEGA65_CORE)/xemu_patched
 	@echo "*** Compiling needed files from mega65-core at $(MEGA65_CORE) ***"
-	cd $(MEGA65_CORE) ; $(MAKE) clean
-	cd $(MEGA65_CORE) ; for dir in src/mega65-freezemenu src/mega65-fdisk src/open-roms ; do $(MAKE) -C $$dir clean || exit 1 ; done
-	find $(MEGA65_CORE) -name "*.o" | xargs -n 100 rm -f
-	find $(MEGA65_CORE) -name "*.M65" | xargs -n 100 rm -f
 	mkdir -p $(MEGA65_CORE)/sdcard-files
-	rm -f `echo $(MEGA65_FP_FILES) | fgrep -v mega65.rom`
-	rm -f $(MEGA65_CORE)/sdcard-files/* $(MEGA65_CORE)/src/mega65-fdisk/*.prg $(MEGA65_CORE)/src/utilities/*.prg
-	rm -f $(MEGA65_CORE)/src/hyppo/HICKUP.rep $(MEGA65_CORE)/src/hyppo/HICKUP.sym
 	cd $(MEGA65_CORE) ; $(MAKE) cc65/bin/cc65
 	cd $(MEGA65_CORE) ; $(MAKE) -C src/mega65-libc
 	cd $(MEGA65_CORE) ; $(MAKE) freezer_files
@@ -69,25 +62,37 @@ recreatememcontent:
 	@echo "*** Generating C files from mega65-core binary results ***"
 	python3 $(TOPDIR)/build/m65-memcontent-generator.py memcontent.c memcontent.h $(MEGA65_FP_FILES)
 
-mega65corefetch:
+cleanmega65core:
+	cd $(MEGA65_CORE) ; $(MAKE) clean
+	cd $(MEGA65_CORE) ; for dir in src/mega65-freezemenu src/mega65-fdisk src/open-roms ; do $(MAKE) -C $$dir clean || exit 1 ; done
+	find $(MEGA65_CORE) -name "*.o" | xargs -n 100 rm -f
+	find $(MEGA65_CORE) -name "*.M65" | xargs -n 100 rm -f
+	mkdir -p $(MEGA65_CORE)/sdcard-files
+	rm -f `echo $(MEGA65_FP_FILES) | fgrep -v mega65.rom`
+	rm -f $(MEGA65_CORE)/sdcard-files/* $(MEGA65_CORE)/src/mega65-fdisk/*.prg $(MEGA65_CORE)/src/utilities/*.prg
+	rm -f $(MEGA65_CORE)/src/hyppo/HICKUP.rep $(MEGA65_CORE)/src/hyppo/HICKUP.sym
+
+$(MEGA65_CORE)/xemu_checked_out:
 	@echo "*** Checking out $(MEGA65_REPO) to $(MEGA65_CORE) at commit-id $(MEGA65_COMMITID) ***"
+	rm -f "$@"
 	rm -fr "$(MEGA65_CORE)"
 	git -c init.defaultBranch=whocares init "$(MEGA65_CORE)"
 	git -C "$(MEGA65_CORE)" remote add origin "$(MEGA65_REPO)"
 	git -C "$(MEGA65_CORE)" fetch --depth 1 origin "$(MEGA65_COMMITID)"
 	git -C "$(MEGA65_CORE)" -c advice.detachedHead=false checkout "$(MEGA65_COMMITID)"
 	git -C "$(MEGA65_CORE)" submodule update --init --recursive --depth 1
-	echo "$(MEGA65_REPO) at commit-id $(MEGA65_COMMITID)" > "$(MEGA65_CORE)/xemu_checked_out.new"
-	date >> "$(MEGA65_CORE)/xemu_checked_out.new"
-	du -sh "$(MEGA65_CORE)" >> "$(MEGA65_CORE)/xemu_checked_out.new"
-	cat "$(MEGA65_CORE)/xemu_checked_out.new" | sed 's/^/| /'
-	mv "$(MEGA65_CORE)/xemu_checked_out.new" "$(MEGA65_CORE)/xemu_checked_out"
+	echo "$(MEGA65_REPO) at commit-id $(MEGA65_COMMITID)" > "$@.new"
+	date >> "$@.new"
+	du -sh "$(MEGA65_CORE)" >> "$@.new"
+	cat "$@.new" | sed 's/^/| /'
+	mv "$@.new" "$@"
 
-mega65patch:
+$(MEGA65_CORE)/xemu_patched:
+	$(MAKE) $(MEGA65_CORE)/xemu_checked_out
 	@echo "*** Patching mega65-core for Xemu at $(MEGA65_CORE) ***"
-	test -f "$(MEGA65_CORE)/xemu_patched" && { echo "*** Already patched ***" ; false ; }
+	@if test -f "$@"; then echo "ERROR: Already patched"; false; fi
 	patch -p1 -d "$(MEGA65_CORE)" < $(MEGA65_PATCH)
-	date > "$(MEGA65_CORE)/xemu_patched"
+	date > "$@"
 
 showmatrix:
 	bash $(TOPDIR)/build/m65-import-matrix2ascii.sh < $(MATRIX_TAB_VHDL)
